### PR TITLE
Solution to Alphabet Cipher

### PR DESCRIPTION
**Pull request by bradlucas**

### CODE REVIEW

**Comment by bradlucas** [comment]
Added wonderland number solution as well

**Comment by gigasquid** [comment]
Thanks for the solutions.  Would you mind just having the pull request be the READMEs that point to your repo?  That way people don't see the solutions before they try it on their own.

Thanks!

**Comment by bradlucas** [comment]
I had a feeling that was I didn't submit the request properly. Do you have a pointer on how to make the request for just the Readme?

**Comment by gigasquid** [comment]
Sure - you can make a new branch that is from the same commit as the this repo by doing 
```
git checkout 211c7e7b9f78a60766a295d0a0be7a12ea5f4647 -b readme
```
Then make the README file changes, commit, and push your new branch.

You can make a pull request from that branch to this repo that should just have the readme file changes in it.    You might be able to edit this one to choose the new branch.  If not, you can open and new one and close this one.

No worries.  If you run into trouble, I can do the changes on my end too to merge it.

Best,
Carin

**Comment by bradlucas** [comment]
Thanks for the suggestion. I'll create the branch as you suggest. I'll probably close this request and open a new one. 

- Brad

**Pull request closed without merging**
